version: "1"
packages:
  - name: "sqlc"
    path: "./../"
    queries: "queries.sql"
    schema: "schema.sql"
    engine: "postgresql"
    driver: "pgx/v4"
    emit_json_tags: true
overrides:
  - go_type: "string"
    db_type: "uuid"
